# @ New version configuration for Skaffold (skaffold/v4beta3)
apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: tixvibe-dev
  artifacts:
    # - image: colson0x1/auth
    - image: us.gcr.io/tixvibe-dev/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    # - image: colson0x1/client
    - image: us.gcr.io/tixvibe-dev/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
          - src: '**/*.jsx'
            dest: .
    # - image: colson0x1/tickets
    - image: us.gcr.io/tixvibe-dev/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    # - image: colson0x1/orders
    - image: us.gcr.io/tixvibe-dev/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    # - image: colson0x1/expiration
    - image: us.gcr.io/tixvibe-dev/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    # - image: colson0x1/payments
    - image: us.gcr.io/tixvibe-dev/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
# @ Old version configuration for Skaffold (skaffold/v2alpha3)
# apiVersion: skaffold/v2alpha3
# kind: Config
# deploy:
#   kubectl:
#     manifests:
#       - ./infra/k8s/*
# build:
#   # local:
#     # push: false
#   googleCloudBuild:
#     projectId: tixvibe-dev
#   artifacts:
#   # - image: colson0x1/auth
#     - image: us.gcr.io/tixvibe-dev/auth
#       context: auth
#       docker:
#         dockerfile: Dockerfile
#       sync:
#         manual:
#           - src: 'src/**/*.ts'
#             dest: .
#   # - image: colson0x1/client
#     - image: us.gcr.io/tixvibe-dev/client
#       context: client
#       docker:
#         dockerfile: Dockerfile
#       sync:
#         manual:
#           - src: 'src/**/*.ts'
#             dest: .
#           - src: 'src/**/*.tsx'
#             dest: .
