name: deploy-manifests

on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save tixvibe
      # Apply all those config files that are placed into the `k8s` dir
      # Also apply everything from `k8s/prod` folder as well
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
